Update my127/my127 to version 0.1.0 which maintains PHP 7 support
my127/workspace pull request #133
Opened 2022-12-05 14:48 UTC by g-foster2

The master branch of php-library is being updated to support PHP 8.x.

2022-12-05 15:29 UTC, dantleech submitted a review, later dismissed

2022-12-08 15:05 UTC, andytson-inviqa requested changes, later dismissed
we should have a 0.3.x branch

2022-12-09 10:36 UTC, andytson-inviqa approved these changes, later dismissed

2022-12-09 10:44 UTC, g-foster2 commented
PHP 7.3, 7.4 and 8.0 tests pass.

2022-12-09 10:45 UTC, andytson-inviqa approved these changes

2022-12-09 10:46 UTC, merged